 language: scala
 scala:
   - "2.11.7"
 jdk:
   - oraclejdk8
   - openjdk7
 script: "sbt -sbt-version 0.13.8 clean base/coverage base/test"
 after_success: "sbt -sbt-version 0.13.8 base/coveralls"
 sudo: false
