 language: scala
 matrix:
   include:
     - jdk: oraclejdk8
       scala: "2.11.7"
       env: COMMAND=sbt clean coverage test && sbt coverageAggregate
     - jdk: openjdk7
       scala: "2.11.7"
       env: COMMAND=sbt clean base/coverage test

 script: $COMMAND
 after_success: "sbt coveralls"
 sudo: false
 addons:
  apt:
    packages:
      - oracle-java8-installer
